name: 📚 Documentation or README.md issue report
description: Report an issue in the project's documentation or README.md file.
title: "[Documentation Bug]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation bug report!
  - type: textarea
    id: documentation-bug-description
    attributes:
      label: Describe the bug ✍️
      description: Enter a brief description about the documentation bug report
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Describe your bug here"
    validations:
      required: true
  - type: textarea
    id: instructions
    attributes:
      label: Provide step by step information reproduce the bug 📄
      description: Enter the description on how you plan to find the bug's solution
      placeholder: Please include a summary, also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Program
      description: Select the program in which you're contributing
      options:
        - GSSoC24
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I follow [CONTRIBUTING GUIDELINE]() of this project.
          required: true
