name: Auto Label Issue Based on Dropdown

on:
  issues:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set label based on dropdown selection
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const contribution = issue.body.match(/Select program in which you are contributing: (.*)/)[1].trim();

            let label = '';
            switch (contribution) {
              case 'GSSoC24':
                label = 'gssoc';
                break;
              case 'Other':
                label = '';
                break;
            }

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: [label]
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
